Repository MrTanoshii/rusty-autoclicker, pull requests merged in 2022-11, with the labels that each got.

#25 Add Icon to Windows binary
  Cargo.toml
  assets/icon-256.ico
  build.rs
  src/lib.rs
  src/main.rs
Labels: enhancement

#27 Small refactors
  src/app.rs
  src/defines.rs
  src/main.rs
Labels: enhancement

#28 Automate release builds
  .cargo/config
  .cargo/config.toml
  .github/workflows/build_artifacts.yml
  .github/workflows/release.yml
Labels: enhancement

#30 ci: remove leading bin dir from release archive
  .github/workflows/build_artifacts.yml
Labels: enhancement

#32 Embed icon in app
  src/main.rs
Labels: bug

#34 docs(README): fetch latest version from tags
  README.md
Labels: documentation

#35 Fix release github action
  .github/workflows/build_artifacts.yml
Labels: bug

#36 refactor: cleanup app.rs
  src/app.rs
Labels: enhancement

#37 Fix coordinates sanitization not allowing negative values
  src/app.rs
Labels: bug
