Repository MrTanoshii/rusty-autoclicker, pull requests merged in 2022-10, with the labels that each got.

#15 Used the image crate to load the icon, instead of hard-coding it as a vector
  Cargo.toml
  src/icon.rs
  src/main.rs
Labels: enhancement

#19 Show remaining clicks when autoclicking a set amount
  src/app.rs
Labels: enhancement, hacktoberfest

#18 Dynamic "button pressed" UI String
  src/app.rs
Labels: bug, hacktoberfest

#20 Fix autoclicking and reduce repetition
  src/app.rs
Labels: bug, enhancement

#22 Feature/add humanlike mouse movement #12
  src/app.rs
  src/constants.rs
  src/lib.rs
  src/main.rs
Labels: enhancement, hacktoberfest
